name: Format Check

on:
  workflow_call:

jobs:
  stylua:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup StyLua
        uses: JohnnyMorganz/stylua-action@v4
        with:
          version: latest
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --check src
